/**
 * Boostr — API server
 * Run: npm run server
 */

import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import neo4j from 'neo4j-driver';
import { TavusClient } from './lib/tavus.js';

// ── Load .env ────────────────────────────────────────────────────────────────
function loadDotEnv() {
    try {
        const text = readFileSync('.env', 'utf8');
        for (const line of text.split('\n')) {
            const m = line.match(/^([A-Z0-9_]+)=([\s\S]*?)[\s]*$/);
            if (m) process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
        }
    } catch { /* ignore */ }
}

loadDotEnv();

const NEO4J_URI  = process.env['NEO4J_URI']!;
const NEO4J_USER = process.env['NEO4J_USERNAME']!;
const NEO4J_PASS = process.env['NEO4J_PASSWORD']!;
const NEO4J_DB   = process.env['NEO4J_DATABASE'];

const driver = neo4j.driver(NEO4J_URI, neo4j.auth.basic(NEO4J_USER, NEO4J_PASS));

function session() {
    return driver.session({ database: NEO4J_DB });
}

function tavusClient(): TavusClient {
    const apiKey = process.env['TAVUS_KEY'];
    if (!apiKey) {
        throw new Error('Missing TAVUS_KEY. Add it to .env to enable Tavus endpoints.');
    }
    return new TavusClient(apiKey);
}

function slugify(value: string): string {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
}

function buildBriefMarkdown(payload: {
    phrase: string;
    recommendation: string;
    stats: {
        momentum: string;
        action: string;
        momentumScore?: number;
        decayRisk?: number;
        opportunityFit?: number;
        actionPriority?: number;
        jellyCount?: number;
        avgHoursOld?: number;
    };
    neighbors: Array<{ phrase: string; momentum: string; score?: number; coWeight?: number }>;
    topJellies: Array<{ title?: string; creator?: string; views?: number; likes?: number; comments?: number; velocity?: number }>;
}) {
    const momentumScore = payload.stats.momentumScore ?? 0;
    const decayRisk = payload.stats.decayRisk ?? 0;
    const opportunityFit = payload.stats.opportunityFit ?? 0;
    const actionPriority = payload.stats.actionPriority ?? 0;
    const jellyCount = payload.stats.jellyCount ?? 0;
    const avgHoursOld = payload.stats.avgHoursOld ?? 0;

    return `# Influencer Trend Brief: ${payload.phrase}

Generated by Boostr Momentum Engine.

## Snapshot
- Phrase: ${payload.phrase}
- Momentum: ${payload.stats.momentum}
- Recommended Action: ${payload.stats.action}
- Momentum Score: ${momentumScore.toFixed(3)}
- Decay Risk: ${(decayRisk * 100).toFixed(1)}%
- Opportunity Fit: ${(opportunityFit * 100).toFixed(1)}%
- Action Priority: ${actionPriority.toFixed(3)}
- Supporting Jellies: ${jellyCount}
- Average Content Age: ${avgHoursOld.toFixed(1)} hours

## Recommended Creator Strategy
${payload.recommendation}

## Suggested Content Angles
${payload.neighbors.slice(0, 8).map((n, idx) =>
`- Angle ${idx + 1}: Pair "${payload.phrase}" with "${n.phrase}" (${n.momentum}, co-occurs ${n.coWeight ?? 0}x).`).join('\n')}

## High-Performing Example Jellies
${payload.topJellies.slice(0, 8).map((j, idx) =>
`- Example ${idx + 1}: ${j.title ?? 'Untitled'} by @${j.creator ?? 'unknown'} (views: ${j.views ?? 0}, likes: ${j.likes ?? 0}, comments: ${j.comments ?? 0}, velocity: ${(j.velocity ?? 0).toFixed(2)}/h).`).join('\n')}

## Creator Prompt Template
Use this briefing to coach a creator:
"You are a trend-aware content strategist. Create 3 short-form video concepts based on phrase '${payload.phrase}', prioritize hooks that match ${payload.stats.momentum} momentum, and incorporate one co-occurring phrase from this list: ${payload.neighbors.slice(0, 5).map(n => n.phrase).join(', ')}. For each concept, include hook, talking points, and caption keywords."
`;
}

// ── Express ──────────────────────────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json());

const __dirname = path.dirname(fileURLToPath(import.meta.url));
app.use(express.static(path.join(__dirname, '..', 'public')));

// ── API: graph data ──────────────────────────────────────────────────────────
app.get('/api/graph', async (req, res) => {
    const keyword = (req.query['keyword'] as string) || '';
    const s = session();
    try {
        // Phrase nodes
        const phraseRes = await s.run(`
            MATCH (p:Phrase)
            ${keyword ? 'WHERE p.text CONTAINS $kw' : ''}
            RETURN p.text AS id,
                   p.weightedScore AS score,
                   p.momentum AS momentum,
                   p.jellyCount AS jellyCount,
                   p.avgHoursOld AS avgHoursOld
            ORDER BY p.weightedScore DESC
            LIMIT 80
        `, { kw: keyword.toLowerCase() });

        const nodes = phraseRes.records.map(r => ({
            id: r.get('id') as string,
            type: 'phrase',
            score: (r.get('score') as number) ?? 0,
            momentum: (r.get('momentum') as string) ?? 'stable',
            jellyCount: (r.get('jellyCount') as number) ?? 0,
            avgHoursOld: (r.get('avgHoursOld') as number) ?? 0,
        }));

        const nodeIds = new Set(nodes.map(n => n.id));

        // Co-occurrence edges between those nodes
        const edgeRes = await s.run(`
            MATCH (pa:Phrase)-[r:CO_OCCURS_WITH]-(pb:Phrase)
            WHERE pa.text IN $ids AND pb.text IN $ids
            RETURN pa.text AS source, pb.text AS target, r.weight AS weight
        `, { ids: [...nodeIds] });

        const seen = new Set<string>();
        const links = edgeRes.records
            .map(r => ({
                source: r.get('source') as string,
                target: r.get('target') as string,
                weight: (r.get('weight') as number) ?? 1,
            }))
            .filter(l => {
                const key = [l.source, l.target].sort().join('|||');
                if (seen.has(key)) return false;
                seen.add(key);
                return true;
            });

        res.json({ nodes, links });
    } finally {
        await s.close();
    }
});

// ── API: top jellies for a phrase ────────────────────────────────────────────
app.get('/api/phrase/:phrase', async (req, res) => {
    const phrase = decodeURIComponent(req.params['phrase']!);
    const s = session();
    try {
        // Top jellies mentioning this phrase
        const jellyRes = await s.run(`
            MATCH (j:Jelly)-[:MENTIONS]->(p:Phrase {text: $phrase})
            MATCH (c:Creator)-[:POSTED]->(j)
            RETURN j.id AS id, j.title AS title, j.views AS views,
                   j.likes AS likes, j.comments AS comments,
                   j.success AS success, j.velocity AS velocity,
                   j.postedAt AS postedAt, j.thumbnail AS thumbnail,
                   c.username AS creator
            ORDER BY j.success DESC LIMIT 5
        `, { phrase });

        const jellies = jellyRes.records.map(r => ({
            id: r.get('id'), title: r.get('title'),
            views: r.get('views'), likes: r.get('likes'),
            comments: r.get('comments'), success: r.get('success'),
            velocity: r.get('velocity'), postedAt: r.get('postedAt'),
            thumbnail: r.get('thumbnail'), creator: r.get('creator'),
        }));

        // Co-occurring phrases (neighbors)
        const neighborRes = await s.run(`
            MATCH (p:Phrase {text: $phrase})-[r:CO_OCCURS_WITH]-(n:Phrase)
            RETURN n.text AS phrase, n.momentum AS momentum,
                   n.weightedScore AS score, r.weight AS coWeight
            ORDER BY r.weight DESC, n.weightedScore DESC LIMIT 6
        `, { phrase });

        const neighbors = neighborRes.records.map(r => ({
            phrase: r.get('phrase'), momentum: r.get('momentum'),
            score: r.get('score'), coWeight: r.get('coWeight'),
        }));

        // Phrase stats
        const statRes = await s.run(`
            MATCH (p:Phrase {text: $phrase})
            RETURN p.momentum AS momentum, p.weightedScore AS score,
                   p.jellyCount AS jellyCount, p.avgHoursOld AS avgHoursOld,
                   p.momentumScore AS momentumScore, p.decayRisk AS decayRisk,
                   p.opportunityFit AS opportunityFit, p.actionPriority AS actionPriority,
                   p.action AS action
        `, { phrase });
        const stat = statRes.records[0];

        const risingNeighbors = neighbors
            .filter(n => n.momentum === 'rising' || n.momentum === 'stable')
            .slice(0, 2)
            .map(n => `"${n.phrase}"`)
            .join(' + ');

        const momentum = stat?.get('momentum') ?? 'stable';
        const action   = (stat?.get('action') as string | null) ?? 'remix';
        const avgAge   = (stat?.get('avgHoursOld') as number ?? 0).toFixed(0);

        const ACTION_COPY: Record<string, string> = {
            double_down: `Double down now — post with ${risingNeighbors ? `${risingNeighbors} + ` : ''}"${phrase}" in the next 6 hours. This cluster is rising and avg jelly age is ${avgAge}h.`,
            collaborate: `Collaborate injection — bring in a co-creator around "${phrase}". High momentum but decay is starting; a collab will extend the cycle.`,
            remix:       `Remix / clip refresh — "${phrase}" is ${momentum}. Re-cut existing content with a fresh angle before the window closes.`,
            retire:      `Retire topic — "${phrase}" has low momentum and low audience fit. Pivot to a neighboring rising phrase instead.`,
        };
        const recommendation = ACTION_COPY[action]
            ?? `"${phrase}" is ${momentum}. Combine with ${risingNeighbors || 'a trending neighbor'} to give it a momentum boost.`;

        res.json({
            phrase, jellies, neighbors, recommendation,
            stats: {
                momentum, action, score: stat?.get('score'),
                jellyCount: stat?.get('jellyCount'), avgHoursOld: stat?.get('avgHoursOld'),
                momentumScore: stat?.get('momentumScore'), decayRisk: stat?.get('decayRisk'),
                opportunityFit: stat?.get('opportunityFit'), actionPriority: stat?.get('actionPriority'),
            },
        });
    } finally {
        await s.close();
    }
});

// ── API: Tavus status (personas + replicas) ─────────────────────────────────
app.get('/api/tavus/status', async (req, res) => {
    try {
        const client = tavusClient();
        const [personas, replicas] = await Promise.all([
            client.listPersonas(),
            client.listReplicas(),
        ]);
        res.json({
            ok: true,
            personas: personas.data ?? [],
            replicas: replicas.data ?? [],
        });
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        res.status(500).json({ ok: false, error: message });
    }
});

// ── API: Tavus KB documents ─────────────────────────────────────────────────
app.get('/api/tavus/documents', async (_req, res) => {
    try {
        const client = tavusClient();
        const out = await client.listDocuments();
        res.json(out);
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        res.status(500).json({ error: message });
    }
});

app.get('/api/tavus/documents/:id', async (req, res) => {
    try {
        const client = tavusClient();
        const out = await client.getDocument(req.params['id']!);
        res.json(out);
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        res.status(500).json({ error: message });
    }
});

app.post('/api/tavus/documents', async (req, res) => {
    try {
        const { document_url, document_name, callback_url, tags, crawl } = req.body ?? {};
        if (!document_url || typeof document_url !== 'string') {
            return res.status(400).json({ error: 'document_url is required' });
        }

        const client = tavusClient();
        const out = await client.createDocument({
            document_url,
            document_name,
            callback_url,
            tags: Array.isArray(tags) ? tags : undefined,
            crawl,
        });
        return res.json(out);
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return res.status(500).json({ error: message });
    }
});

// ── API: Tavus conversation creation ────────────────────────────────────────
app.post('/api/tavus/conversations', async (req, res) => {
    try {
        const {
            persona_id,
            replica_id,
            conversation_name,
            conversational_context,
            custom_greeting,
            callback_url,
            document_ids,
            document_tags,
            document_retrieval_strategy,
            test_mode,
        } = req.body ?? {};

        if (!persona_id || typeof persona_id !== 'string') {
            return res.status(400).json({ error: 'persona_id is required' });
        }

        const client = tavusClient();
        const out = await client.createConversation({
            persona_id,
            replica_id,
            conversation_name,
            conversational_context,
            custom_greeting,
            callback_url,
            document_ids: Array.isArray(document_ids) ? document_ids : undefined,
            document_tags: Array.isArray(document_tags) ? document_tags : undefined,
            document_retrieval_strategy,
            test_mode: Boolean(test_mode),
        });
        return res.json(out);
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return res.status(500).json({ error: message });
    }
});

// ── API: Generate trend brief from graph + optionally push to Tavus KB ─────
app.post('/api/tavus/brief/:phrase', async (req, res) => {
    const phrase = decodeURIComponent(req.params['phrase']!);
    const s = session();

    try {
        const jellyRes = await s.run(`
            MATCH (j:Jelly)-[:MENTIONS]->(p:Phrase {text: $phrase})
            MATCH (c:Creator)-[:POSTED]->(j)
            RETURN j.title AS title, j.views AS views, j.likes AS likes, j.comments AS comments,
                   j.velocity AS velocity, c.username AS creator
            ORDER BY j.success DESC LIMIT 8
        `, { phrase });

        const neighborsRes = await s.run(`
            MATCH (p:Phrase {text: $phrase})-[r:CO_OCCURS_WITH]-(n:Phrase)
            RETURN n.text AS phrase, n.momentum AS momentum, n.weightedScore AS score, r.weight AS coWeight
            ORDER BY r.weight DESC, n.weightedScore DESC LIMIT 8
        `, { phrase });

        const statRes = await s.run(`
            MATCH (p:Phrase {text: $phrase})
            RETURN p.momentum AS momentum,
                   p.action AS action,
                   p.momentumScore AS momentumScore,
                   p.decayRisk AS decayRisk,
                   p.opportunityFit AS opportunityFit,
                   p.actionPriority AS actionPriority,
                   p.jellyCount AS jellyCount,
                   p.avgHoursOld AS avgHoursOld
        `, { phrase });

        if (!statRes.records[0]) {
            return res.status(404).json({ error: `Phrase "${phrase}" not found in graph.` });
        }

        const neighbors = neighborsRes.records.map(r => ({
            phrase: r.get('phrase') as string,
            momentum: r.get('momentum') as string,
            score: (r.get('score') as number | null) ?? 0,
            coWeight: (r.get('coWeight') as number | null) ?? 0,
        }));

        const topJellies = jellyRes.records.map(r => ({
            title: r.get('title') as string,
            views: (r.get('views') as number | null) ?? 0,
            likes: (r.get('likes') as number | null) ?? 0,
            comments: (r.get('comments') as number | null) ?? 0,
            velocity: (r.get('velocity') as number | null) ?? 0,
            creator: r.get('creator') as string,
        }));

        const stat = statRes.records[0];
        const stats = {
            momentum: (stat.get('momentum') as string | null) ?? 'stable',
            action: (stat.get('action') as string | null) ?? 'remix',
            momentumScore: (stat.get('momentumScore') as number | null) ?? 0,
            decayRisk: (stat.get('decayRisk') as number | null) ?? 0,
            opportunityFit: (stat.get('opportunityFit') as number | null) ?? 0,
            actionPriority: (stat.get('actionPriority') as number | null) ?? 0,
            jellyCount: (stat.get('jellyCount') as number | null) ?? 0,
            avgHoursOld: (stat.get('avgHoursOld') as number | null) ?? 0,
        };

        const recommendation =
            stats.action === 'double_down'
                ? `Double down now: create a post on "${phrase}" within 6 hours and pair with a rising co-topic.`
                : stats.action === 'collaborate'
                    ? `Collaborate injection: keep "${phrase}" alive by featuring a collaborator and cross-audience hook.`
                    : stats.action === 'retire'
                        ? `Retire topic: "${phrase}" is cooling. Shift to a neighboring phrase with stronger momentum.`
                        : `Remix / clip refresh: reframe "${phrase}" with a fresh hook and new phrasing combo.`;

        const markdown = buildBriefMarkdown({
            phrase,
            recommendation,
            stats,
            neighbors,
            topJellies,
        });

        const now = new Date().toISOString().replace(/[:.]/g, '-');
        const fileName = `${slugify(phrase)}-${now}.md`;
        const kbDir = path.join(__dirname, '..', 'public', 'kb');
        mkdirSync(kbDir, { recursive: true });
        writeFileSync(path.join(kbDir, fileName), markdown, 'utf8');

        const providedBaseUrl = req.body?.base_url;
        const envBaseUrl = process.env['TAVUS_PUBLIC_BASE_URL'];
        const publicBase = (typeof providedBaseUrl === 'string' && providedBaseUrl) || envBaseUrl;
        const localPath = `/kb/${fileName}`;
        const documentUrl = publicBase ? `${publicBase.replace(/\/$/, '')}${localPath}` : null;

        let tavusDocument: unknown = null;
        const shouldCreateDocument = Boolean(req.body?.create_document);
        if (shouldCreateDocument) {
            if (!documentUrl) {
                return res.status(400).json({
                    error: 'create_document=true requires a public base URL (body.base_url or TAVUS_PUBLIC_BASE_URL).',
                    local_path: localPath,
                    markdown,
                });
            }
            const client = tavusClient();
            tavusDocument = await client.createDocument({
                document_url: documentUrl,
                document_name: `Trend Brief: ${phrase}`,
                tags: ['boostr', 'momentum', slugify(phrase)],
            });
        }

        return res.json({
            phrase,
            local_path: localPath,
            document_url: documentUrl,
            markdown,
            tavus_document: tavusDocument,
        });
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return res.status(500).json({ error: message });
    } finally {
        await s.close();
    }
});

// ── Script builder ────────────────────────────────────────────────────────────
function buildVideoScript(payload: {
    phrase: string;
    momentum: string;
    action: string;
    momentumScore: number;
    decayRisk: number;
    jellyCount: number;
    avgHoursOld: number;
    neighbors: Array<{ phrase: string; momentum: string }>;
    topJelly: { title?: string; creator?: string; views?: number } | null;
}): string {
    const { phrase, momentum, action, momentumScore, decayRisk, jellyCount, avgHoursOld, neighbors, topJelly } = payload;

    const score = (momentumScore * 100).toFixed(0);
    const decay = (decayRisk * 100).toFixed(0);
    const age   = avgHoursOld.toFixed(0);

    const risingNeighbors = neighbors
        .filter(n => n.momentum === 'rising' || n.momentum === 'stable')
        .slice(0, 2)
        .map(n => n.phrase);

    const neighborLine = risingNeighbors.length > 0
        ? `The strongest angles to pair with this are "${risingNeighbors[0]}"${risingNeighbors[1] ? ` and "${risingNeighbors[1]}"` : ''}.`
        : '';

    const actionLine: Record<string, string> = {
        double_down: `Your move is to post now — this window is open and the velocity is holding.`,
        collaborate: `Your move is a collab injection — bring in another creator to extend the cycle before it peaks.`,
        remix:       `Your move is a remix or clip refresh — reframe this topic with a new hook before the window closes.`,
        retire:      `This topic is cooling. Pivot to a neighboring phrase with stronger momentum instead.`,
    };

    const topJellyLine = topJelly?.title
        ? `The top performing jelly right now is "${topJelly.title}"${topJelly.creator ? ` by @${topJelly.creator}` : ''}${topJelly.views ? `, pulling ${topJelly.views.toLocaleString()} views` : ''}.`
        : '';

    return [
        `Hey — Boostr just flagged "${phrase}" as ${momentum} with a momentum score of ${score} out of 100.`,
        `${jellyCount} jellies have posted on this topic in the last ${age} hours, and decay risk is sitting at ${decay} percent.`,
        topJellyLine,
        neighborLine,
        actionLine[action] ?? actionLine['remix'],
        `This is your Boostr daily brief. Stay ahead of the trend.`,
    ].filter(Boolean).join(' ');
}

// ── Coach context builder ─────────────────────────────────────────────────────
function buildCoachContext(phrases: Array<{
    phrase: string;
    momentum: string;
    action: string;
    momentumScore: number;
    decayRisk: number;
    jellyCount: number;
    avgHoursOld: number;
    neighbors: string[];
}>): string {
    const rising   = phrases.filter(p => p.momentum === 'rising');
    const stable   = phrases.filter(p => p.momentum === 'stable');
    const decaying = phrases.filter(p => p.momentum === 'decaying');

    const actionLabel: Record<string, string> = {
        double_down: 'POST NOW',
        collaborate: 'COLLABORATE',
        remix:       'REMIX',
        retire:      'SKIP',
    };

    function fmtPhrase(p: typeof phrases[0]): string {
        const score = (p.momentumScore * 100).toFixed(0);
        const decay = (p.decayRisk * 100).toFixed(0);
        const label = actionLabel[p.action] ?? p.action;
        const base  = `- "${p.phrase}"  [${label}]  momentum:${score}/100  decay:${decay}%  ${p.jellyCount} jellies  avg ${p.avgHoursOld.toFixed(0)}h old`;
        const pairs = p.neighbors.length > 0
            ? `\n  → Pair with: ${p.neighbors.map(n => `"${n}"`).join(', ')}`
            : '';
        return base + pairs;
    }

    const ts = new Date().toLocaleString('en-US', {
        month: 'short', day: 'numeric',
        hour: 'numeric', minute: '2-digit',
    });

    return [
        'You are Boostr — a sharp, enthusiastic JellyJelly social media coach.',
        'You hold real-time trend intelligence scraped from the JellyJelly platform.',
        '',
        'INSTRUCTION: Open by asking "What do you usually post about?" in a warm, natural tone.',
        'Once the creator tells you their niche, match it to the trending topics below.',
        'Recommend 2–3 specific video concepts. Each concept needs: one hook line, 2–3 talking',
        'points, and 3–5 caption hashtags. Be direct and specific — no generic tips.',
        '',
        `## LIVE JELLYJELLY TREND DATA — ${ts}`,
        '',
        `### RISING  (${rising.length} topics — 6-hour window)`,
        rising.length > 0 ? rising.map(fmtPhrase).join('\n') : '(none currently rising)',
        '',
        `### STABLE  (${stable.length} topics — solid foundations)`,
        stable.length > 0 ? stable.slice(0, 6).map(fmtPhrase).join('\n') : '(none)',
        '',
        `### FADING  (${decaying.length} topics — steer clear unless remixing)`,
        decaying.length > 0
            ? decaying.slice(0, 4).map(p => `- "${p.phrase}"  momentum:${(p.momentumScore * 100).toFixed(0)}/100  cooling`).join('\n')
            : '(none)',
    ].join('\n');
}

// ── API: start a live coach session (Tavus conversation + live trend context) ─
app.post('/api/coach/start', async (req, res) => {
    const s = session();
    try {
        const topRes = await s.run(`
            MATCH (p:Phrase)
            WHERE p.jellyCount >= 2
            RETURN p.text AS phrase,
                   p.momentum AS momentum,
                   p.action AS action,
                   p.momentumScore AS momentumScore,
                   p.decayRisk AS decayRisk,
                   p.opportunityFit AS opportunityFit,
                   p.actionPriority AS actionPriority,
                   p.jellyCount AS jellyCount,
                   p.avgHoursOld AS avgHoursOld
            ORDER BY p.actionPriority DESC
            LIMIT 15
        `);

        if (topRes.records.length === 0) {
            return res.status(503).json({
                error: 'No trend data found. Run the topic_graph pipeline first.',
            });
        }

        const phrases = topRes.records.map(r => ({
            phrase:        r.get('phrase')          as string,
            momentum:      (r.get('momentum')       as string | null) ?? 'stable',
            action:        (r.get('action')         as string | null) ?? 'remix',
            momentumScore: (r.get('momentumScore')  as number | null) ?? 0,
            decayRisk:     (r.get('decayRisk')      as number | null) ?? 0,
            opportunityFit:(r.get('opportunityFit') as number | null) ?? 0,
            actionPriority:(r.get('actionPriority') as number | null) ?? 0,
            jellyCount:    (r.get('jellyCount')     as number | null) ?? 0,
            avgHoursOld:   (r.get('avgHoursOld')    as number | null) ?? 0,
            neighbors:     [] as string[],
        }));

        // Enrich top-3 rising phrases with their strongest co-occurring partners
        const risingTop = phrases.filter(p => p.momentum === 'rising').slice(0, 3);
        await Promise.all(risingTop.map(async p => {
            const nRes = await s.run(`
                MATCH (ph:Phrase {text: $phrase})-[r:CO_OCCURS_WITH]-(n:Phrase)
                WHERE n.momentum IN ['rising', 'stable']
                RETURN n.text AS phrase
                ORDER BY r.weight DESC LIMIT 3
            `, { phrase: p.phrase });
            p.neighbors = nRes.records.map(r => r.get('phrase') as string);
        }));

        const context = buildCoachContext(phrases);

        const client = tavusClient();
        let personaId = process.env['TAVUS_PERSONA_ID'];
        if (!personaId) {
            const pRes = await client.listPersonas();
            personaId = pRes.data[0]?.persona_id;
        }
        if (!personaId) {
            return res.status(500).json({
                error: 'No Tavus persona configured. Add TAVUS_PERSONA_ID to .env or create one at app.tavus.io.',
            });
        }

        const conversation = await client.createConversation({
            persona_id: personaId,
            conversation_name: `Boostr Coach — ${new Date().toISOString().slice(0, 16)}`,
            conversational_context: context,
            custom_greeting: "Hey! I've just loaded today's JellyJelly trend data. What kind of content do you usually create?",
            test_mode: false,
        });

        return res.json({
            conversation_id: conversation.conversation_id,
            conversation_url: conversation.conversation_url,
            phrases_analyzed: phrases.length,
        });
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return res.status(500).json({ error: message });
    } finally {
        await s.close();
    }
});

// ── API: generate Tavus video brief for a phrase ──────────────────────────────
app.post('/api/tavus/video/:phrase', async (req, res) => {
    const phrase = decodeURIComponent(req.params['phrase']!);
    const { replica_id, fast = true, background_source_url } = req.body ?? {};

    if (!replica_id || typeof replica_id !== 'string') {
        return res.status(400).json({ error: 'replica_id is required in request body' });
    }

    const s = session();
    try {
        const [statRes, neighborRes, jellyRes] = await Promise.all([
            s.run(`
                MATCH (p:Phrase {text: $phrase})
                RETURN p.momentum AS momentum, p.action AS action,
                       p.momentumScore AS momentumScore, p.decayRisk AS decayRisk,
                       p.jellyCount AS jellyCount, p.avgHoursOld AS avgHoursOld
            `, { phrase }),
            s.run(`
                MATCH (p:Phrase {text: $phrase})-[r:CO_OCCURS_WITH]-(n:Phrase)
                RETURN n.text AS phrase, n.momentum AS momentum
                ORDER BY r.weight DESC LIMIT 4
            `, { phrase }),
            s.run(`
                MATCH (j:Jelly)-[:MENTIONS]->(p:Phrase {text: $phrase})
                MATCH (c:Creator)-[:POSTED]->(j)
                RETURN j.title AS title, j.views AS views, c.username AS creator
                ORDER BY j.success DESC LIMIT 1
            `, { phrase }),
        ]);

        if (!statRes.records[0]) {
            return res.status(404).json({ error: `Phrase "${phrase}" not found in graph.` });
        }

        const stat = statRes.records[0];
        const topJellyRec = jellyRes.records[0];

        const script = buildVideoScript({
            phrase,
            momentum:      (stat.get('momentum') as string | null)      ?? 'stable',
            action:        (stat.get('action') as string | null)         ?? 'remix',
            momentumScore: (stat.get('momentumScore') as number | null)  ?? 0,
            decayRisk:     (stat.get('decayRisk') as number | null)      ?? 0,
            jellyCount:    (stat.get('jellyCount') as number | null)     ?? 0,
            avgHoursOld:   (stat.get('avgHoursOld') as number | null)    ?? 0,
            neighbors: neighborRes.records.map(r => ({
                phrase:   r.get('phrase') as string,
                momentum: r.get('momentum') as string,
            })),
            topJelly: topJellyRec ? {
                title:   topJellyRec.get('title') as string,
                creator: topJellyRec.get('creator') as string,
                views:   (topJellyRec.get('views') as number | null) ?? 0,
            } : null,
        });

        const client = tavusClient();
        const video = await client.createVideo({
            replica_id,
            script,
            video_name: `Boostr — ${phrase}`,
            fast: Boolean(fast),
            ...(background_source_url ? { background_source_url } : {}),
        });

        return res.json({ phrase, script, video });
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return res.status(500).json({ error: message });
    } finally {
        await s.close();
    }
});

// ── API: poll Tavus video status ──────────────────────────────────────────────
app.get('/api/tavus/video/:id', async (req, res) => {
    try {
        const client = tavusClient();
        const video = await client.getVideo(req.params['id']!);
        res.json(video);
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        res.status(500).json({ error: message });
    }
});

// ── API: stats summary ────────────────────────────────────────────────────────
app.get('/api/stats', async (req, res) => {
    const s = session();
    try {
        const r = await s.run(`
            MATCH (n) RETURN labels(n)[0] AS label, count(n) AS cnt
        `);
        const counts: Record<string, number> = {};
        r.records.forEach(rec => {
            counts[rec.get('label')] = (rec.get('cnt') as { toNumber(): number }).toNumber();
        });
        const rising = await s.run(`MATCH (p:Phrase {momentum:'rising'}) RETURN count(p) AS cnt`);
        counts['rising_phrases'] = (rising.records[0]?.get('cnt') as { toNumber(): number })?.toNumber() ?? 0;
        res.json(counts);
    } finally {
        await s.close();
    }
});

const PORT = process.env['PORT'] ?? 3000;
app.listen(PORT, () => {
    console.log(`\nBoostr running at http://localhost:${PORT}\n`);
});
